server/file/urls.py
from django.conf.urls import url
from . import views

app_name = 'file'

urlpatterns =[
    url(r'^$', views.index, name='index'),
]

server/server/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    url(r'^$', views.index_redirect, name='views_redirect'),
    url(r'^file/', include('file.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/file/models.py
from django.db import models

# Create your models here.
class File(models.Model):
    file = models.FileField()

    def __str__(self):
        return self.file.name

server/file/views.py
from django.shortcuts import render
from django.core.files.storage import FileSystemStorage

from . models import File
import os, datetime
import pefile
import struct
import io
import requests
import os.path,time

from . import trail


IMAGE_FILE_MACHINE_I386=332
IMAGE_FILE_MACHINE_IA64=512
IMAGE_FILE_MACHINE_AMD64=34404

# Create your views here.

def index(request):
    if request.method == 'POST' and request.FILES['file']:
        upload_file = request.FILES['file']
        extension = os.path.splitext(upload_file.name)[1]
        rename = datetime.datetime.now().strftime("%Y_%m_%d %H_%M_%S") + extension
        fss = FileSystemStorage()

        filename = fss.save(rename, upload_file)

        file = File(file=rename)

        file.save()

        upload_file_path = fss.path(filename)

        md5=trail.hash_value(upload_file_path)
        f = upload_file_path
        fl = open(f, "rb")
        s = fl.read(5)
        byte_range = bytearray(s)
        date_header, timestamp = struct.unpack('>BL', byte_range)
        print(date_header)
        if ( date_header!=77):
            print(" Not an EXE file")
        else:
            fl.seek(60)
            s = fl.read(4)
            header_offset = struct.unpack("<L", s)[0]
            fl.seek(header_offset + 4)
            s = fl.read(2)
            machine = struct.unpack("<H", s)[0]

            if machine == IMAGE_FILE_MACHINE_I386:
                print(" Image Type = IA-32 (32-bit x86)")
                fp = open('PE Analysis.txt', 'a')
                fp.write("Image Type = IA-32 (32-bit x86)")
                fp.write('\n\n')
                fp.close()
            elif machine == IMAGE_FILE_MACHINE_IA64:
                print(" Image Type = IA-64 (Itanium)")
                fp = open('PE Analysis.txt', 'a')
                fp.write("Image Type = IA-64 (Itanium)")
                fp.write('\n\n')
                fp.close()
            elif machine == IMAGE_FILE_MACHINE_AMD64:
                print(" Image Type = AMD64 (64-bit x86)")
                fp = open('PE Analysis.txt', 'a')
                fp.write("Image Type = AMD64 (64-bit x86)")
                fp.write('\n\n')
                fp.close()
            else:
                print(" Unknown architecture")

            print('\n File Size = ' + trail.file_size(f))
            print('\n Last Modified Date = %s' % time.ctime(os.path.getmtime(f)))
            print('\n Created Date = %s' % time.ctime(os.path.getctime(f)))

            fp = open('PE Analysis.txt', 'a')
            fp.write('File Size = ' + trail.file_size(f))
            fp.write('\n\nLast Modified Date: %s' % time.ctime(os.path.getmtime(f)))
            fp.write('\n\nCreated Date: %s' % time.ctime(os.path.getctime(f)))
            fp.write('\n')
            fp.write('\n')
            fp.close()
        fl.close()
        virustotal=trail.VT_Request('eca6223108ae025265a09a1723ddc2d7396c31ab41f720428f9a9fc7bd4cb95e',md5,upload_file_path)
        if(isinstance(virustotal,str)):
            output=virustotal
        else:
             md=virustotal[0]
             sha1=virustotal[1]
             sha256=virustotal[2]
             positives=virustotal[3]
             total=virustotal[4]


        return render(request, 'file/hello.html', {'upload_file_path': upload_file_path,'md5':virustotal[0],'sha1':virustotal[1],'sha256':virustotal[2],'positives':virustotal[3],'total':virustotal[4]})

    else:
        return render(request, 'file/index.html')

server/server/views.py
from django.shortcuts import redirect

def index_redirect(request):
    return redirect('/file/')

server/file/templates/file/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1"/>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'file/css/bootstrap.css' %}"/>
    </head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <a class="navbar-brand" href="https://sourcecodster.com">Sourcecodester</a>
        </div>
    </nav>
    <div class="col-md-3"></div>
    <div class="col-md-6 well">
        <h3 class="text-primary">Python - Simple File Upload With Django</h3>
        <hr style="border-top:1px dotted #000;"/>
        {% block body %}
        {% endblock %}
    </div>
</body>
</html>

server/file/templates/file/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body bgcolor="#1abc9c">



{% if upload_file_path %}
    Uploaded at: <label class="text-primary">{{ upload_file_path }}</label>

 {% endif %}

</br></br>


{% if md5 %}
    md5: <label class="text-primary">{{ md5 }}</label>

 {% endif %}

</br></br>

{% if sha1 %}
    sha1: <label class="text-primary">{{ sha1}}</label>

 {% endif %}


</br></br>

{% if sha256 %}
    sha256: <label class="text-primary">{{ sha256 }}</label>

 {% endif %}


</br></br>

{% if positives  %}
    hit count positives : <label class="text-primary">{{ positives }} </label> /  {{ total }}
</br></br><font color="red" >  file is malicious </font>


 {% endif %}



</body>
</html>

server/file/templates/file/index.html
{% extends 'file/base.html' %}
{% block body %}
<form method="POST" action="{% url 'file:index' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <input type="file" name="file" required="required"/>
        <br />
        <button type="submit" class="btn btn-sm btn-primary"><span class="glyphicon glyphicon-upload"></span> Upload</button>
    </div>
</form>

 {% if upload_file_path %}
    Uploaded at: <label class="text-primary">{{ upload_file_path }}</label>
 {% endif %}




{% endblock %}